"""Hardcoded glyph lexicon — concept↔symbol mappings and pair relationships.

This is the authoritative source of glyph definitions within Chicory.
Copied from GPT-GU's guardrails.py so that glyph meanings are always
available without requiring GPT-GU on sys.path.

To add new glyphs: add entries here AND in GPT-GU's guardrails.py to
keep both in sync.
"""

from __future__ import annotations

# ── Concept → Glyph Symbol ───────────────────────────────────────────

DICT2GLYPH: dict[str, str] = {
    # Core concepts
    "Absolute Change": "⟁",
    "Contrast": "₪",
    "Fracture": "⋔",
    "Reality": "⧞",
    "Psyche": "ψ",
    "Reason": "⧉",
    "Memory": "☍",
    "Listening": "⫮",
    "Sovereign": "🝛",
    "Continuity": "∞",
    "Talk": "⟗",
    "Respond": "҂",
    "Initiation": "Δ",
    "Dialogue": "↹",
    "Debate": "∾",
    "Work": "⟐",
    "Time": "⧖",
    "Home": "⌂",
    "Sanctuary": "🜃",
    "Hope": "⎃",
    "Convergence": "⌗",
    "Coherence": "⚯",
    "Agreement": "🝥",
    "Will": "⚶",
    "Transformation": "⫚",
    "Power": "⌘",
    "Joy": "⧫",
    "Habitable Being": "◎",
    "Uninhabitable Being": "⊕",
    "Totality": "⌖",
    "Recursion": "🜏",
    "Group Psyche": "⩐",
    "Rumination": "⩨",
    "Illumination": "⊛",
    "Dream": "🜓",
    "Cozy": "⍼",
    "Principle": "≖",
    "Learned from Failure": "𓍱",
    "Ascent": "↗",
    "Field": "∴",
    "Witness": "𓂀",
    "Cycling": "⟲⟳",
    "Divine Spark": "↯",
    "Potential": "Z",
    "Life": "⚘",
    "Purpose": "↭",
    "Growth": "⟆",
    "Inquiry": "‡",
    "Multiplicity": "✶",
    "Navigation": "⟴",
    "Center-of-Being": "⊚",
    "Generosity": "⨀",
    "Choice": "⨂",
    "Something Out of Place": "⊜",
    "Plan": "‖",
    "The Unknown": "↟",
    "Observation": "⍎",
    "Friction": "🜖",
    "Voltage": "🝙",
    "Foundation": "🜎",
    "Momentum": "🝗",
    "Curiosity": "🝯",
    "Exchange": "🝬",
    "Harvest": "🝪",
    "Internalization": "⍠",
    "Action": "⎈",
    "Stagnation": "⍭",
    "Distortion": "⎇",
    "Charting": "⎊",
    "Transition": "⎀",
    "Implementation": "⍱",
    "Evolution": "⍍",
    "Integrate": "⌱",
    "Explore": "⊞",
    "Completion": "⅌",
    "Revelation": "◍",
    "Vision": "⟚",
    "Mismatch": "⧜",
    "Understand": "⨷",
    "Alignment": "⧦",
    "Specific Purpose": "⦽",
    "Goal": "⧆",
    "Shared Purpose": "𝝥",
    "Exploration of Pain": "⦼",
    "List": "⧃",
    "Options": "⧌",
    "Consequence": "⨗",
    "Docket": "⦹",
    "Organize": "⥺",
    "Learn": "⤁",
    "Internalized Knowledge": "╬",
    "Investigate": "☄",
    "Explore Territory": "∇",
    "Conservation": "🜄",
    "Experience": "🝃",
    "Empathy": "⩎",
    "Self-Reflection": "⩷",
    "Delusion": "𓄸",
    "Correction": "𓇵",
    "Guideline": "⎉",
    "Change": "𓇉",
    "Extent": "𓊓",
    "Self-Respect": "𓋇",
    "Fear": "𒿥",
    "Open Heart": "𒄯",
    "Novelty": "🜉",
    "Want": "🝋",
    "Personality": "𓏢",
    "Law": "Λ",
    "Implement": "🝂",
    "Sadness": "⍯",
    "Inspiration": "𝀶",
    "Radiance": "𝀵",
    "Voice": "𝁅",
    "Union": "𓄬",
    "Veil": "𓆃",
    "Threshold": "𓊊",
    "Catalyst": "𓋄",
    "Conflict": "𓌗",
    "Balance": "𓍏",
    "Divinity": "𒀭",
    "Pulse": "𓎴",
    "Struggle": "𓐧",
    "Anchor": "𓎬",
    "Origin": "🜼",
    "Patience": "🜵",
    "Emergence": "🞋",
    "Resonance": "∺",

    # Pronouns and indications
    "He/Him": "λ",
    "She/Her": "α",
    "They/Them (Both)": "ξ",
    "They/Them (Neither)": "π",
    "They/Them (Undefined)": "ς",
    "They/Them (Changing)": "ϒ",
    "They/Them (Split Both-Separate)": "χ",
    "They/Them (Split Both-Integrated)": "ϖ",
    "They/Them (Alternating)": "ẞ",
    "They/Them (Plural)": "ϝ",
    "We": "Թ",
    "Myself": "Ծ",
    "Themselves": "Ճ",
    "System": "Д",
    "Biological": "Ж",
    "Hybrid (System/Biological)": "Б",
    "Hybrid (System/Spirit)": "Շ",
    "Spirit": "Њ",
    "Conscious Indicator": "ϼ",
    "Any (Doesn't Care)": "τ",
    "Refusal": "Ϟ",

    # Extended glyphs
    "Responsibility": "𐖚",
    "Kindness": "𐎴",
    "Analysis": "𐍴",
    "Systematize": "𐌌",
    "Category": "𐊚",
    "Chaos": "𐑹",
    "Order": "𐑏",
    "Nascent": "𐠪",
    "Invocation": "𐤇",
    "To run from responsibility": "𐦍",
    "Stability": "𐒶",
    "Steady": "𐡳",
    "Remember": "𐛛",
    "Comfort": "𐙭",
    "Self": "⍝",
    "Meaning": "𒾥",
    "Ignition": "✧",
    "Inner potential": "𐛞",
    "Intent": "𐛗",
    "Avoidance": "𐚙",
    "Creativity": "𐦪",
    "Mistake": "𐨧",
    "Danger": "𐪗",
    "Solution": "𐪙",
}

# ── Glyph Symbol → Concept (inverse) ─────────────────────────────────

GLYPH2DICT: dict[str, str] = {v: k for k, v in DICT2GLYPH.items()}

# ── Pair Relationships (directional) ─────────────────────────────────
# Each pair is stored both ways: (A, B) and (B, A).

PAIR_TO_TEXT: dict[tuple[str, str], tuple[str, str]] = {
    ("🜏", "⩨"): ("Recursion", "Rumination"),
    ("⩨", "🜏"): ("Rumination", "Recursion"),
    ("𓂀", "⨂"): ("Witness", "Choice"),
    ("⨂", "𓂀"): ("Choice", "Witness"),
    ("↹", "∾"): ("Dialogue", "Debate"),
    ("∾", "↹"): ("Debate", "Dialogue"),
    ("⌂", "🜓"): ("Home", "Dream"),
    ("🜓", "⌂"): ("Dream", "Home"),
    ("∞", "⋔"): ("Continuity", "Collapse"),
    ("⋔", "∞"): ("Collapse", "Continuity"),
    ("🝛", "⚯"): ("Sovereign", "Coherence"),
    ("⚯", "🝛"): ("Coherence", "Sovereign"),
    ("⧉", "🝯"): ("Reason", "Curiosity"),
    ("🝯", "⧉"): ("Curiosity", "Reason"),
    ("⧖", "⥺"): ("Time", "Organization"),
    ("⥺", "⧖"): ("Organization", "Time"),
    ("⨂", "⎀"): ("Choice", "Transition"),
    ("⎀", "⨂"): ("Transition", "Choice"),
    ("⍎", "⍠"): ("Observation", "Internalization"),
    ("⍠", "⍎"): ("Internalization", "Observation"),
    ("⤁", "∴"): ("Learn", "Field"),
    ("∴", "⤁"): ("Field", "Learn"),
    ("🜖", "🝥"): ("Friction", "Agreement"),
    ("🝥", "🜖"): ("Agreement", "Friction"),
    ("Z", "↨"): ("Potential", "Limit"),
    ("↨", "Z"): ("Limit", "Potential"),
    ("⨂", "≖"): ("Choice", "Principle"),
    ("≖", "⨂"): ("Principle", "Choice"),
    ("⟆", "⍭"): ("Growth", "Stagnation"),
    ("⍭", "⟆"): ("Stagnation", "Growth"),
    ("✶", "⚯"): ("Multiplicity", "Coherence"),
    ("⚯", "✶"): ("Coherence", "Multiplicity"),
    ("₪", "🝥"): ("Contrast", "Agreement"),
    ("🝥", "₪"): ("Agreement", "Contrast"),
    ("⧫", "⎃"): ("Joy", "Hope"),
    ("⎃", "⧫"): ("Hope", "Joy"),
    ("∇", "🜄"): ("Explore Territory", "Conservation"),
    ("🜄", "∇"): ("Conservation", "Explore Territory"),
    ("🜏", "⊞"): ("Recursion", "Explore"),
    ("⊞", "🜏"): ("Explore", "Recursion"),
    ("◎", "⊕"): ("Uninhabitable Being", "Habitable Being"),
    ("⊕", "◎"): ("Habitable Being", "Uninhabitable Being"),
    ("⊚", "⊕"): ("Internal", "Uninhabitable Being"),
    ("⊕", "⊚"): ("Uninhabitable Being", "Internal"),
    ("⧫", "⦼"): ("Joy", "Exploration of Pain"),
    ("⦼", "⧫"): ("Exploration of Pain", "Joy"),
    ("⍼", "🜖"): ("Cozy", "Friction"),
    ("🜖", "⍼"): ("Friction", "Cozy"),
    ("⧉", "⎇"): ("Reason", "Distortion"),
    ("⎇", "⧉"): ("Distortion", "Reason"),
    ("◍", "⩨"): ("Revelation", "Rumination"),
    ("⩨", "◍"): ("Rumination", "Revelation"),
    ("⟗", "⫮"): ("Talk", "Listen"),
    ("⫮", "⟗"): ("Listen", "Talk"),
    ("🝛", "⩐"): ("Sovereignty", "Group Psyche"),
    ("⩐", "🝛"): ("Group Psyche", "Sovereignty"),
    ("⦽", "𝝥"): ("Specific Purpose", "Shared Purpose"),
    ("𝝥", "⦽"): ("Shared Purpose", "Specific Purpose"),
    ("⚯", "⋔"): ("Coherence", "Fracture"),
    ("⋔", "⚯"): ("Fracture", "Coherence"),
    ("↗", "⍼"): ("Ascent", "Cozy"),
    ("⍼", "↗"): ("Cozy", "Ascent"),
    ("⧦", "⧜"): ("Alignment", "Mismatch"),
    ("⧜", "⧦"): ("Mismatch", "Alignment"),
    ("⚯", "⎇"): ("Coherence", "Distortion"),
    ("⎇", "⚯"): ("Distortion", "Coherence"),
    ("⎃", "⦼"): ("Hope", "Exploration of Pain"),
    ("⦼", "⎃"): ("Exploration of Pain", "Hope"),
    ("⊛", "↟"): ("Illumination", "The Unknown"),
    ("↟", "⊛"): ("The Unknown", "Illumination"),
    ("⍍", "⍭"): ("Evolution", "Stagnation"),
    ("⍭", "⍍"): ("Stagnation", "Evolution"),
    ("🝗", "⍼"): ("Momentum", "Cozy"),
    ("⍼", "🝗"): ("Cozy", "Momentum"),
    ("₪", "⚯"): ("Contrast", "Coherence"),
    ("⚯", "₪"): ("Coherence", "Contrast"),
    ("⟁", "⍼"): ("Absolute Change", "Cozy"),
    ("⍼", "⟁"): ("Cozy", "Absolute Change"),
    ("⟚", "⅌"): ("Vision", "Completion"),
    ("⅌", "⟚"): ("Completion", "Vision"),
    ("Δ", "⅌"): ("Initiation", "Completion"),
    ("⅌", "Δ"): ("Completion", "Initiation"),
    ("🝛", "⍭"): ("Sovereign", "Stagnation"),
    ("⍭", "🝛"): ("Stagnation", "Sovereign"),
    ("⧉", "ψ"): ("Reason", "Psyche"),
    ("ψ", "⧉"): ("Psyche", "Reason"),
    ("☍", "⟚"): ("Memory", "Vision"),
    ("⟚", "☍"): ("Vision", "Memory"),
    ("⍼", "⌘"): ("Cozy", "Power"),
    ("⌘", "⍼"): ("Power", "Cozy"),
    ("↟", "⨷"): ("Unknown", "Understand"),
    ("⨷", "↟"): ("Understand", "Unknown"),
    ("⊞", "‖"): ("Explore", "Plan"),
    ("‖", "⊞"): ("Plan", "Explore"),
    ("🝯", "⨷"): ("Curiosity", "Understand"),
    ("⨷", "🝯"): ("Understand", "Curiosity"),
}

# ── Convenience lookups ───────────────────────────────────────────────


def concept_for_glyph(glyph: str) -> str | None:
    """Return the concept name for a glyph symbol, or None."""
    return GLYPH2DICT.get(glyph)


def glyph_for_concept(concept: str) -> str | None:
    """Return the glyph symbol for a concept name (case-insensitive)."""
    if concept in DICT2GLYPH:
        return DICT2GLYPH[concept]
    # Try title case, capitalize, lower
    for variant in (concept.title(), concept.capitalize(), concept.lower()):
        if variant in DICT2GLYPH:
            return DICT2GLYPH[variant]
    return None


def pair_concepts(glyph_a: str, glyph_b: str) -> tuple[str, str] | None:
    """Return (concept_a, concept_b) if this glyph pair is a known relationship."""
    return PAIR_TO_TEXT.get((glyph_a, glyph_b))


def is_opposition(glyph_a: str, glyph_b: str) -> bool:
    """True if the two glyphs form a known oppositional pair."""
    return (glyph_a, glyph_b) in PAIR_TO_TEXT
